name: Uglyfy

on:
  push:
    branches: [ gh-pages ]

jobs:
  uglyfy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Minify Action
      uses: anthonyftwang/minify-action@v1.0.1
#     - name: Auto Minify
#       # You may pin to the exact commit or the version.
#       # uses: nizarmah/auto-minify@7028a7a4b79ccdc7e00f351baed61c59d07690ee
#       uses: nizarmah/auto-minify@v2.1.1
#       with:
#         # Directory that contains the files you want to minify. Defaults to current directory (.)
#         directory: /
#         # Directory that contains the minified files. Defaults to same directory
#         output: /
#         # Overwrites the existing files with the minified version. Defaults to false.
#         overwrite: true
    # Auto commits minified files to the repository
    # Ignore it if you don't want to commit the files to the repository 
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
